(() => {
'use strict';

const DB_URL='https://lnmgieielbqqqvboonzj.supabase.co/functions/v1/drawlab-state';
const ROOT_V3=location.pathname.includes('/drawlab-sa/v3/');
const LOCAL_URL=ROOT_V3?'data/v3-state.json':'v3/data/v3-state.json';
const GAMES=['Daily Lotto','Lotto','PowerBall'];
const LIVE_STRATEGIES=['Hot 6M','Weighted Historical','Cold 6M','Diversified Coverage','Frozen Alpha'];
const NAV=[
  ['dashboard','⌂','Dashboard','Today, portfolio and latest evidence'],
  ['live','●','Live','Pre-draw entries and settlements'],
  ['models','◈','Models','What every model is actually testing'],
  ['market','↗','Market','Expected value and player crowding'],
  ['research','⌁','Research','Walk-forward evidence and challengers'],
  ['archive','▦','Archive','Draw history, records and methodology']
];
const INFO={
  'Hot 6M':{role:'Prediction control',refresh:'Every draw',hypothesis:'Tests whether recent high-frequency numbers persist into the next draw.',method:'Ranks six-month, three-month and last-10 frequency windows with deterministic tie-breaking.',verdict:'Keep locked as a research control. No corrected evidence of durable prediction alpha.'},
  'Weighted Historical':{role:'Prediction control',refresh:'Every draw',hypothesis:'Tests a fixed blend of long-term frequency, six-month frequency, momentum and gap signals.',method:'Versioned weighted score with deterministic spread construction.',verdict:'Retain the historical experiment; do not treat the current blend as proven alpha.'},
  'Cold 6M':{role:'Prediction control',refresh:'Every draw',hypothesis:'Tests whether recently underrepresented numbers revert toward expected frequency.',method:'Low six-month frequency is primary, absence/gap secondary, then deterministic spread construction.',verdict:'Interesting raw cells exist, but none survive multiple-testing correction. Keep as falsification research.'},
  'Diversified Coverage':{role:'Portfolio control',refresh:'Every draw',hypothesis:'Tests whether low-overlap lines improve portfolio coverage across several simultaneous strategies.',method:'Builds a deterministic range-spread line after the other live lines are known.',verdict:'Useful for portfolio construction, not evidence that any individual line is more likely.'},
  'Frozen Alpha':{role:'Persistence control',refresh:'Never within rule era',hypothesis:'Tests the simplest policy: generate one legal deterministic line and keep it unchanged.',method:'A locked snapshot that only resets when the lottery itself changes the legal ticket format.',verdict:'Keep permanently as the clean dynamic-vs-fixed benchmark.'}
};

let S={};
let SOURCE='fallback';
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('en-ZA',{maximumFractionDigits:2}).format(Number(n||0));
const money=n=>n==null?'—':`R${fmt(n)}`;
const pct=n=>n==null?'—':`${Number(n).toFixed(2)}%`;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const tone=n=>Number(n)>0?'good':Number(n)<0?'bad':'muted';
const statusTone=s=>{s=String(s||'').toLowerCase();if(s.includes('enter')||s.includes('healthy')||s.includes('randomness_consistent')||s.includes('empirical_signal'))return'good';if(s.includes('watch')||s.includes('insufficient')||s.includes('preparing'))return'warn';if(s.includes('review')||s.includes('anomaly'))return'bad';return'muted';};
const dateFmt=v=>{try{return new Date(v).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'});}catch{return v||'—';}};
const timeFmt=v=>{try{return new Date(v).toLocaleString('en-ZA',{dateStyle:'medium',timeStyle:'short'});}catch{return v||'—';}};
const gameCode=g=>g==='Daily Lotto'?'DL':g==='PowerBall'?'PB':'L';

async function fetchJSON(url,timeout=6500){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${url}${url.includes('?')?'&':'?'}t=${Date.now()}`,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(String(r.status));return await r.json();}finally{clearTimeout(t);}}
function localFrozen(rows){if(!Array.isArray(rows)||!rows.length)return null;const lines={};for(const r of rows)lines[r.game]={numbers:r.numbers||[],bonus:r.bonus};return{name:'Frozen Alpha',version:'1.0',locked:true,generated_at:rows[0]?.generated_on,lines};}
function merge(local,db){const out={...(local||{})};if(db?.database_status==='ok'){
  SOURCE='database';out.db=db;
  if(db.research)out.research={...(out.research||{}),...db.research};
  if(db.retrospective)out.retrospective=db.retrospective;
  if(db.shadow_research)out.shadow_research=db.shadow_research;
  if(db.ev_hunter)out.ev_hunter=db.ev_hunter;
  if(db.crowd_model)out.crowd_model=db.crowd_model;
  if(db.integrity_audit)out.integrity_audit=db.integrity_audit;
  out.live_league=db.live_league||out.live_league||[];out.hall_of_records=db.hall_of_records||out.hall_of_records||[];out.recent_results=db.recent_results||out.recent_results||[];out.pending_tickets=db.pending_tickets||out.pending_tickets||[];out.experiment_queue=db.experiment_queue||out.experiment_queue||[];out.database_history=db.history||out.database_history||[];
  const f=localFrozen(db.frozen);if(f)out.frozen={...(out.frozen||{}),...f};
 }else SOURCE='fallback';return out;}

function setupNav(){
  $('sideNav').innerHTML=NAV.map(([id,ico,label,sub])=>`<button data-view="${id}" class="${id==='dashboard'?'active':''}"><span class="nav-icon">${ico}</span><span><b>${label}</b><small>${sub}</small></span></button>`).join('');
  $('mobileNav').innerHTML=NAV.slice(0,5).map(([id,ico,label])=>`<button data-view="${id}" class="${id==='dashboard'?'active':''}"><b>${ico}</b><span>${label}</span></button>`).join('')+`<button data-view="archive"><b>▦</b><span>Archive</span></button>`;
  document.body.addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)show(b.dataset.view);const g=e.target.closest('[data-goto]');if(g)show(g.dataset.goto);const m=e.target.closest('[data-model]');if(m)openModel(m.dataset.model);});
}
function show(id){if(!NAV.some(x=>x[0]===id))id='dashboard';document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));const n=NAV.find(x=>x[0]===id);$('pageTitle').textContent=n?.[2]||'DrawLab';$('pageSub').textContent=n?.[3]||'';history.replaceState(null,'',`${location.pathname}${location.search}#${id}`);window.scrollTo({top:0,behavior:'smooth'});}

function balls(nums,bonus){return `<div class="balls">${(nums||[]).map(n=>`<span class="ball">${n}</span>`).join('')}${bonus!=null?`<span class="ball bonus">${bonus}</span>`:''}</div>`;}
function pill(text,kind=''){return `<span class="pill ${kind}">${esc(String(text||'—').replaceAll('_',' '))}</span>`;}
function metric(label,value,sub,kind=''){return `<div class="metric"><span>${label}</span><strong class="${kind}">${value}</strong><small>${sub}</small></div>`;}
function resultCard(r){return `<article class="result-row"><div class="game-badge">${gameCode(r.game)}</div><div><span class="eyebrow">${esc(r.game)}</span><h3>${dateFmt(r.date||r.draw_date)}</h3></div>${balls(r.numbers||r.main_numbers,r.bonus??r.bonus_number)}<div class="result-meta"><span>${esc(r.verification_status||r.payout_type||'verified')}</span><b>${r.payout_divisions!=null?`${r.payout_divisions} payout divisions`:r.payout_type==='exact'?'Exact payout':'Official result'}</b></div></article>`;}

function renderShell(){
  const dbOk=S.db?.database_status==='ok';const cloudOk=String(S.cloud_status||'ok').toLowerCase()==='ok';
  $('sourceChip').textContent=dbOk?'SUPABASE PRIMARY':'AUDIT FALLBACK';$('healthChip').className=`health ${dbOk&&cloudOk?'good':'warn'}`;$('healthChip').innerHTML=`<i></i>${dbOk&&cloudOk?'SYSTEM HEALTHY':'DEGRADED MODE'}`;
  $('railStatus').innerHTML=`<b>${dbOk?'Database synchronized':'Repository fallback active'}</b><span>${dbOk?`${fmt(S.db?.counts?.draws)} draws · ${fmt(S.db?.counts?.tickets)} live tickets`:'Static validated snapshots remain available.'}</span>`;
  $('updated').textContent=`${SOURCE==='database'?'Database read':'Validated fallback'} · ${timeFmt(S.db?.generated_at||S.generated_at)}`;
}

function renderDashboard(){
  const p=S.portfolio||{};const ev=S.ev_hunter?.current||{};const audit=S.integrity_audit||{};const wf=S.research?.walk_forward||[];const sig=wf.filter(r=>['strong_above_chance','interesting_above_chance'].includes(r.evidence));
  $('heroVerdict').textContent=sig.length?'Evidence worth reviewing':'No proven prediction edge';$('heroCopy').textContent=sig.length?'Some historical cells cleared a raw threshold. Replication and correction still decide whether they mean anything.':'The current number-prediction models remain research controls. Market structure and player behaviour are the more promising directions.';
  $('dashboardMetrics').innerHTML=[metric('Portfolio net',money(p.net),`${fmt(p.settled)} settled tickets`,tone(p.net)),metric('Live ROI',pct(p.roi_pct),'Paper-trading portfolio',tone(p.roi_pct)),metric('Best live match',`${p.best_matches||0}`,'Main-number matches'),metric('Verified draws',fmt(S.db?.counts?.draws||0),'Supabase archive'),metric('Integrity',String(audit.overall_status||'preparing').replaceAll('_',' '),'Randomness audit')].join('');
  $('todayDecisions').innerHTML=GAMES.map(g=>{const r=ev[g]||{};return `<div class="decision-card"><div class="decision-top"><div><span>${gameCode(g)}</span><h3>${g}</h3></div>${pill(r.decision||'PREPARING',statusTone(r.decision))}</div><div class="decision-value"><span>Conservative EV</span><strong class="${tone(r.conservative_roi_pct)}">${r.conservative_roi_pct==null?'—':`${Number(r.conservative_roi_pct)>0?'+':''}${pct(r.conservative_roi_pct)}`}</strong></div><div class="decision-grid"><div><span>Ticket</span><b>${money(r.ticket_cost)}</b></div><div><span>Jackpot</span><b>${money(r.advertised_jackpot)}</b></div><div><span>Expected return</span><b>${money(r.conservative_return??r.expected_return)}</b></div></div><p>${esc(r.mechanic||'Waiting for current economics.')}</p></div>`;}).join('');
  const live=(S.live_league||[]).slice(0,5);$('dashboardLeague').innerHTML=live.map((r,i)=>`<div class="rank-row" data-model="${esc(r.strategy)}"><span class="rank">${i+1}</span><div><b>${esc(r.strategy)}</b><small>${esc(INFO[r.strategy]?.role||'Live research')}</small></div><div class="rank-stat"><span>ROI</span><b class="${tone(r.roi_pct)}">${pct(r.roi_pct)}</b></div><div class="rank-stat"><span>Best</span><b>${r.best_matches||0}</b></div></div>`).join('')||'<div class="empty">Live league is waiting for its next sync.</div>';
  $('dashboardResults').innerHTML=(S.recent_results||[]).slice(0,5).map(resultCard).join('')||'<div class="empty">No recent results available.</div>';
  const crowd=S.crowd_model?.games||{};const signal=GAMES.map(g=>[g,crowd[g]]).filter(([,x])=>x?.status==='empirical_signal').map(([g])=>g);
  $('dashboardInsight').innerHTML=`<span class="eyebrow">LATEST RESEARCH POSITION</span><h3>${signal.length?`Crowding signal in ${signal.join(', ')}`:'Prediction remains unproven'}</h3><p>${signal.length?'The player-choice model has an out-of-sample crowding signal worth monitoring. That affects expected prize sharing, not draw probability.':'No live number-selection strategy currently has corrected evidence of durable draw-prediction alpha. EV Hunter therefore focuses on whether the prize economics justify entering at all.'}</p><button class="text-btn" data-goto="research">Open evidence →</button>`;
}

function renderLive(){
  const pending=S.pending_tickets||[];$('pendingCount').textContent=fmt(pending.length);
  $('pendingList').innerHTML=pending.length?pending.slice(0,30).map(t=>`<div class="ticket-row"><div><span class="eyebrow">${esc(t.game)}</span><h3>${esc(t.strategy)}</h3><small>${dateFmt(t.date)} · v${esc(t.version||t.strategy_version||'1.0')}</small></div>${balls(t.numbers,t.bonus)}<div><span class="muted">Cost</span><b>${money(t.cost)}</b></div>${pill(t.status||'Pending','warn')}</div>`).join(''):'<div class="empty">No pending live tickets right now.</div>';
  const f=S.frozen||{};$('frozenGrid').innerHTML=GAMES.map(g=>{const l=f.lines?.[g];if(!l)return'';return `<div class="card frozen"><div class="card-head"><div>${pill('LOCKED CONTROL','purple')}<h3>${g}</h3></div><span>v${esc(f.version||'1.0')}</span></div>${balls(l.numbers,l.bonus)}<p>Never re-ranked because of wins or losses. It only resets if the legal ticket format changes.</p></div>`;}).join('');
  $('liveLeague').innerHTML='<div class="table-row header"><div>Strategy</div><div>Tickets</div><div>Settled</div><div>Spend</div><div>Won</div><div>Net / ROI</div></div>'+(S.live_league||[]).map(r=>`<div class="table-row" data-model="${esc(r.strategy)}"><div><b>${esc(r.strategy)}</b><small>${esc(INFO[r.strategy]?.role||'')}</small></div><div>${fmt(r.tickets)}</div><div>${fmt(r.settled)}</div><div>${money(r.spend)}</div><div>${money(r.won)}</div><div><b class="${tone(r.net)}">${money(r.net)}</b><small class="${tone(r.roi_pct)}">${pct(r.roi_pct)}</small></div></div>`).join('');
}

function renderModels(){
  const liveMap=Object.fromEntries((S.live_league||[]).map(r=>[r.strategy,r]));
  $('liveModelGrid').innerHTML=LIVE_STRATEGIES.map(name=>{const i=INFO[name],r=liveMap[name]||{};return `<article class="model-card" data-model="${esc(name)}"><div class="model-head"><div>${pill(i.role,name==='Frozen Alpha'?'purple':'')}<h3>${name} <span>v1.0</span></h3></div><button>Open →</button></div><p>${esc(i.hypothesis)}</p><div class="model-stats"><div><span>Refresh</span><b>${esc(i.refresh)}</b></div><div><span>Settled</span><b>${fmt(r.settled||0)}</b></div><div><span>ROI</span><b class="${tone(r.roi_pct)}">${pct(r.roi_pct)}</b></div><div><span>Best</span><b>${r.best_matches||0}</b></div></div><div class="model-verdict">${esc(i.verdict)}</div></article>`;}).join('');
  const disc=S.research?.strategy_discovery?.games||{};$('challengerGrid').innerHTML=GAMES.map(g=>{const r=disc[g]||{};if(r.status==='insufficient_data')return `<div class="card"><div class="card-head">${pill('WAITING FOR DATA','warn')}<b>${g}</b></div><p>${esc(r.reason||'Not enough compatible draws.')}</p></div>`;const c=r.selected||{},test=r.held_out_test?.candidate||{},base=r.held_out_test?.best_current_v1||{};return `<div class="card"><div class="card-head"><div>${pill(String(r.status||'preparing').toUpperCase(),r.status==='promotion_candidate'?'good':r.status?.includes('promising')?'purple':'')}<h3>${g}</h3></div><span>${esc(c.family||'research')}</span></div><p>${esc(c.name||'No challenger selected yet.')}</p><div class="mini-grid"><div><span>Held-out avg</span><b>${test.avg_matches??'—'}</b></div><div><span>Best v1</span><b>${base.avg_matches??'—'}</b></div><div><span>Test draws</span><b>${fmt(test.samples||0)}</b></div><div><span>Evidence</span><b>${esc(String(test.evidence||'—').replaceAll('_',' '))}</b></div></div></div>`;}).join('');
  $('modelArchitecture').innerHTML=[['1','Prediction controls','Hot, Cold and Weighted test historical-number hypotheses. Their job is to fail cleanly if no signal exists.'],['2','Portfolio controls','Diversified Coverage and Frozen Alpha test construction and persistence rather than “lucky” numbers.'],['3','Player behaviour','Crowd Model estimates how other people choose equal-probability combinations, because sharing changes monetary value.'],['4','Prize economics','EV Hunter decides whether a draw is worth entering. A negative-EV draw remains a skip even if a low-crowding line exists.']].map(([n,t,p])=>`<div class="method-row"><b>${n}</b><div><h3>${t}</h3><p>${p}</p></div></div>`).join('');
}

function renderMarket(){
  const ev=S.ev_hunter||{},cur=ev.current||{};$('marketCards').innerHTML=GAMES.map(g=>{const r=cur[g]||{},l=r.anti_crowd_line||{};const br=g==='Daily Lotto'?'Not applicable':money(r.break_even_jackpot);return `<article class="market-card"><div class="market-head"><div><span class="eyebrow">${g}</span><h3>${esc(r.draw_date||'Upcoming')}</h3></div>${pill(r.decision||'PREPARING',statusTone(r.decision))}</div><div class="market-score"><span>Conservative modelled ROI</span><strong class="${tone(r.conservative_roi_pct)}">${r.conservative_roi_pct==null?'—':`${Number(r.conservative_roi_pct)>0?'+':''}${pct(r.conservative_roi_pct)}`}</strong></div><div class="market-grid"><div><span>Ticket</span><b>${money(r.ticket_cost)}</b></div><div><span>Advertised jackpot</span><b>${money(r.advertised_jackpot)}</b></div><div><span>Expected return</span><b>${money(r.conservative_return??r.expected_return)}</b></div><div><span>Break-even jackpot</span><b>${br}</b></div><div><span>Predicted lines</span><b>${r.predicted_line_volume?fmt(r.predicted_line_volume):'—'}</b></div><div><span>Other jackpot winners</span><b>${r.expected_other_jackpot_winners_uniform??'—'}</b></div></div><div class="low-share"><span>LOW-SHARING RESEARCH LINE</span>${balls(l.numbers,l.bonus)}<p>${esc(l.meaning||'Equal draw probability; intended only to reduce prize-sharing risk.')}</p></div></article>`;}).join('');
  const crowd=S.crowd_model?.games||{};$('crowdGrid').innerHTML=GAMES.map(g=>{const r=crowd[g]||{},fx=r.largest_effects||[];return `<div class="card"><div class="card-head"><div>${pill(String(r.status||'preparing').toUpperCase(),statusTone(r.status))}<h3>${g}</h3></div><b>n=${fmt(r.samples||0)}</b></div><div class="mini-grid"><div><span>Holdout</span><b>${fmt(r.holdout_samples||0)}</b></div><div><span>RMSE improvement</span><b class="${tone(r.holdout_improvement_pct)}">${r.holdout_improvement_pct==null?'—':pct(r.holdout_improvement_pct)}</b></div></div><div class="effect-list">${fx.length?fx.slice(0,5).map(x=>`<div><span>${esc(String(x.feature).replaceAll('_',' '))}</span><b>${x.coefficient>0?'+':''}${Number(x.coefficient).toFixed(3)}</b></div>`).join(''):'<div><span>Waiting for more exact sales/winner observations</span><b>—</b></div>'}</div><p>${esc(r.interpretation||'Exploratory until out-of-sample evidence is strong enough.')}</p></div>`;}).join('');
  const s=ev.shadow_summary||{};$('marketShadow').innerHTML=`<div class="shadow-summary">${metric('Entries',fmt(s.tickets||0),'Prospective only')}${metric('Settled',fmt(s.settled||0),'Future confirmations')}${metric('Spend',money(s.spend||0),'Research stake')}${metric('Won',money(s.won||0),'Exact settlement')}${metric('ROI',pct(s.roi_pct),'Only qualifying draws',tone(s.roi_pct))}</div><div class="notice"><b>Entry discipline:</b> EV Hunter may legitimately say SKIP for weeks or months. That is expected. It cannot create a ticket simply because the number-selection model looks interesting.</div>`;
  $('evMethod').innerHTML=`<h3>${esc(ev.model_version||'EV Hunter v2.0')}</h3><p>${esc(ev.methodology?.gate||'Uses conservative structural expected value for the entry gate.')}</p><div class="method-chips"><span>Daily Lotto: pool/rolldown</span><span>Lotto: fixed + pari-mutuel tiers</span><span>PowerBall: fixed + variable tiers</span><span>Crowding uplift excluded from gate</span></div>`;
}

function renderResearch(){
  const audit=S.integrity_audit?.games||{};$('integrityGrid').innerHTML=GAMES.map(g=>{const r=audit[g]||{},f=r.frequency||{},p=r.pairs||{},o=r.serial_overlap||{};return `<div class="card"><div class="card-head"><div>${pill(String(r.status||'preparing').toUpperCase(),statusTone(r.status))}<h3>${g}</h3></div><b>n=${fmt(r.draws||0)}</b></div><div class="audit"><div><span>Most extreme number</span><b>${f.most_extreme_number??'—'} · pAdj ${f.p_adjusted??'—'}</b></div><div><span>Most extreme pair</span><b>${Array.isArray(p.most_extreme_pair)?p.most_extreme_pair.join(' · '):'—'} · pAdj ${p.p_adjusted??'—'}</b></div><div><span>Serial overlap</span><b>${o.observed_overlap??'—'} vs ${o.expected_overlap??'—'}</b></div><div><span>Minimum corrected p</span><b>${r.minimum_adjusted_p??'—'}</b></div></div><p>${esc(r.interpretation||'Waiting for enough compatible draws.')}</p></div>`;}).join('');
  const retro=normalizeRetro(S.retrospective);$('retroGame').innerHTML=GAMES.map(g=>`<option>${g}</option>`).join('');$('retroGame').onchange=()=>renderRetro($('retroGame').value,retro);renderRetro($('retroGame').value,retro);
  const wf=S.research?.walk_forward||[];$('holdGame').innerHTML=GAMES.map(g=>`<option>${g}</option>`).join('');$('holdGame').onchange=()=>renderHold($('holdGame').value,wf);renderHold($('holdGame').value,wf);
  const q=S.experiment_queue||[];$('experimentQueue').innerHTML=q.length?q.map(x=>`<div class="queue-row"><div><h3>${esc(x.title)}</h3><p>${esc(x.hypothesis)}</p></div>${pill(String(x.status||'proposed').toUpperCase(),x.status==='running'?'good':x.status==='candidate'?'purple':'warn')}</div>`).join(''):'<div class="empty">No queued experiments.</div>';
}
function normalizeRetro(retro){if(retro?.summary)return retro.summary;if(Array.isArray(retro)){const out={};for(const r of retro){(out[r.game]||={})[r.strategy]=r;}return out;}return{};}
function renderRetro(game,retro){const rows=retro?.[game]||{};$('retroTable').innerHTML='<div class="table-row retro header"><div>Strategy</div><div>Tickets</div><div>Avg matches</div><div>≥2 rate</div><div>Best</div><div>ROI*</div></div>'+Object.entries(rows).map(([name,r])=>`<div class="table-row retro"><div><b>${esc(name)}</b></div><div>${fmt(r.tickets||r.samples||0)}</div><div>${r.avg_matches??'—'}</div><div>${r.ge2_rate==null?'—':pct(r.ge2_rate)}</div><div>${r.best_matches||0}</div><div class="${tone(r.roi_pct)}">${pct(r.roi_pct)}</div></div>`).join('');}
function renderHold(game,wf){const rows=wf.filter(r=>r.game===game),h=[1,2,4,8,20,'never'];let html='<div class="hold-grid"><div class="hold-cell head">Strategy</div>'+h.map(x=>`<div class="hold-cell head">${x==='never'?'Never':x}</div>`).join('');for(const s of LIVE_STRATEGIES.filter(x=>x!=='Frozen Alpha')){html+=`<div class="hold-cell strategy">${s}</div>`;for(const x of h){const r=rows.find(y=>y.strategy===s&&String(y.horizon)===String(x));html+=`<div class="hold-cell"><b>${r?.avg_matches??'—'}</b><span>${r?`${r.ge2_rate}% ≥2 · n=${r.samples}`:'not run'}</span></div>`;}}$('holdMatrix').innerHTML=html+'</div>';}

function renderArchive(){
  const dbH=S.database_history||S.db?.history||[],q=S.research?.data_quality||{},map=Object.fromEntries(dbH.map(x=>[x.game,x]));$('historyGrid').innerHTML=GAMES.map(g=>{const d=map[g]||{},m=q[g]||{};return `<div class="card"><div class="card-head"><div><span class="eyebrow">${g}</span><h3>${fmt(d.draws||m.draws||0)} verified draws</h3></div>${pill(String(m.status||'unknown').toUpperCase(),m.status==='usable'?'good':'warn')}</div><p>${dateFmt(d.first_draw||m.first_draw)} → ${dateFmt(d.last_draw||m.last_draw)}</p><div class="scope"><i style="width:${Math.min(100,Math.max(4,(Number(m.draws||0)/Math.max(1,Number(d.draws||m.draws||1)))*100))}%"></i></div><small>${esc(m.rule_scope||'Validated archive')}</small></div>`;}).join('');
  $('archiveResults').innerHTML=(S.recent_results||[]).slice(0,12).map(resultCard).join('');
  $('records').innerHTML=(S.hall_of_records||[]).length?(S.hall_of_records||[]).map(r=>`<div class="record-row"><span class="rank">#${r.rank}</span><div><h3>${esc(r.strategy)} · ${esc(r.game)}</h3><p>${dateFmt(r.date)} · ${(r.numbers||[]).join(' · ')}${r.bonus!=null?` + ${r.bonus}`:''}</p></div><div><b>${r.matches||0} match${Number(r.matches)===1?'':'es'}</b><span>${money(r.won)}</span></div></div>`).join(''):'<div class="empty">No settled live records yet.</div>';
  const rules=[['DL','Daily Lotto · 5/36','Current archive uses the same 5/36 main-number space. Prize economics are sales-funded and modelled with the roll-down mechanism.'],['L','Lotto · 6/58 → 6/52','Legacy 6/58 remains archived. Current modelling starts at the 6/52 rule boundary rather than mixing incompatible spaces.'],['PB','PowerBall · 5/50 + special ball','Main-number history remains 5/50. The special-ball pool changed by rule era and is modelled separately.']];$('ruleEras').innerHTML=rules.map(([c,t,p])=>`<div class="method-row"><b>${c}</b><div><h3>${t}</h3><p>${p}</p></div></div>`).join('');
  $('methodology').innerHTML=(S.principles||[]).map((p,i)=>`<div class="method-row"><b>${i+1}</b><div><h3>${esc(p)}</h3></div></div>`).join('');
}

function openModel(name){const i=INFO[name];if(!i)return;const r=(S.live_league||[]).find(x=>x.strategy===name)||{};$('drawer').classList.add('open');$('drawerBackdrop').classList.add('open');$('drawer').setAttribute('aria-hidden','false');$('drawerBody').innerHTML=`${pill(i.role,name==='Frozen Alpha'?'purple':'')}<h2>${esc(name)} <span>v1.0</span></h2><p class="drawer-intro">${esc(i.hypothesis)}</p><div class="drawer-stats"><div><span>Refresh</span><b>${esc(i.refresh)}</b></div><div><span>Settled</span><b>${fmt(r.settled||0)}</b></div><div><span>ROI</span><b class="${tone(r.roi_pct)}">${pct(r.roi_pct)}</b></div><div><span>Best match</span><b>${r.best_matches||0}</b></div></div><section><span class="eyebrow">METHOD</span><p>${esc(i.method)}</p></section><section><span class="eyebrow">CURRENT VERDICT</span><p>${esc(i.verdict)}</p></section><section><span class="eyebrow">GOVERNANCE</span><p>v1.0 remains immutable. Any formula change creates a new version and starts a fresh prospective evidence trail.</p></section>`;}
function closeDrawer(){$('drawer').classList.remove('open');$('drawerBackdrop').classList.remove('open');$('drawer').setAttribute('aria-hidden','true');}

function renderAll(){renderShell();renderDashboard();renderLive();renderModels();renderMarket();renderResearch();renderArchive();}
async function boot(){setupNav();$('drawerClose').onclick=closeDrawer;$('drawerBackdrop').onclick=closeDrawer;const [dbR,localR]=await Promise.allSettled([fetchJSON(DB_URL),fetchJSON(LOCAL_URL,5000)]);const db=dbR.status==='fulfilled'?dbR.value:null,local=localR.status==='fulfilled'?localR.value:{};S=merge(local,db);renderAll();show(location.hash.replace('#','')||'dashboard');}
document.addEventListener('DOMContentLoaded',boot,{once:true});
})();